#!/usr/bin/env bash

# Load configuration
source ~/.ansiblealigne.conf

# Check if a name was passed
NAME_PLAYBOOK="$1"

if [ -z "$NAME_PLAYBOOK" ]; then
  read -rp "What is the name of your playbook? " NAME_PLAYBOOK
fi

echo "Name is: $NAME_PLAYBOOK"

read -rp "do you wanna initialize a role? :" NAME_ROLE

if [ -z "$NAME_ROLE" ]; then
  echo "No role initialized. Going to menu"
else
  echo "wir tun mal so als würde das funktionieren"
  echo "Initialisiere rolle"
  echo "bla"
  echo "bla"    echo "bla"
  echo "bla"
  echo "bla"
  echo "bla"
  echo "bla"
  echo "bla"
fi
