#!/usr/bin/env bash

# Load configuration
source ~/.ansiblealigne.conf


# Check if a name was passed
NAME_PLAYBOOK="$1"

# Check if a role name was Provided on the 2nd argument
NAME_ROLE="$2"

if [ -z "$NAME_PLAYBOOK" ]; then
  # If no name was provided, prompt the user for a name
  read -rp "${INP_CLR}Please enter a name for your new playbook: " NAME_PLAYBOOK
fi   
# Check if the playbook name is empty after the prompt
if [ -z "$NAME_PLAYBOOK" ]; then
  echo "${ERR_CLR}No playbook name provided. Exiting."
  exit 1
fi
# Check if a role name was not provided on the cmd line
if [ -z "$NAME_ROLE" ]; then
  ROLE_CREATION_DECIDER="" # Initialize variable

    # Loop to check User Role Desition inpit
    while true; do
      read -rp "${INP_CLR}Do you want to craate a Role for your Playbook abd have it initialized? (Y/N) " ROLE_CREATION_DECIDER
      # Check Input
      if [[ "$ROLE_CREATION_DECIDER" =~ ^[YyJjNn]$ ]]; then
            break # Leave Loop wehn input is correct
      else
        echo "${ERR_CLR}Allowed inputs: Y N and y n"
      fi
    done

    # Role Decition
    if [[ "$ROLE_CREATION_DECIDER" =~ ^[YyJj]$ ]]; then
      read -rp "${INP_CLR}Name your Role:" NAME_ROLE
    else
      echo "There will be no Role initialized"
      NAME_ROLE="" # Left empty
    fi
fi

if [ -z "$NAME_ROLE" ]; then
  echo "No role initialized. Going to menu"
else
  echo "Initializing role: $NAME_ROLE"
  ansible-galaxy init "$NAME_ROLE"
fi

echo "${HLP_CLR}Role was initialized."